# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tf.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08tf.proto\x12\x06protos\"m\n\x07\x63luster\x12\n\n\x02ps\x18\x01 \x01(\t\x12\x0f\n\x07workers\x18\x02 \x03(\t\x12\r\n\x05layer\x18\x03 \x03(\x05\x12\x12\n\nlearn_rate\x18\x04 \x01(\x01\x12\x12\n\nbatch_size\x18\x05 \x01(\x05\x12\x0e\n\x06master\x18\x06 \x01(\t\"#\n\x06status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03mes\x18\x02 \x01(\t\";\n\x0bworker_note\x12\x0c\n\x04w_ip\x18\x01 \x01(\t\x12\x0b\n\x03w_f\x18\x02 \x01(\t\x12\x11\n\tnext_time\x18\x03 \x01(\x01\"\x1d\n\rworker_fin_ip\x12\x0c\n\x04w_ip\x18\x01 \x03(\t\"(\n\x04\x64\x61ta\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\tindex_gap\x18\x02 \x01(\x05\"\x16\n\x04note\x12\x0e\n\x06notice\x18\x01 \x01(\t\"$\n\x0c\x61rray_weight\x12\t\n\x01w\x18\x01 \x03(\x01\x12\t\n\x01\x62\x18\x02 \x03(\x01\"\x1b\n\x04step\x12\x13\n\x0bstep_number\x18\x01 \x01(\x05\"\x1d\n\x05\x64\x65lta\x12\t\n\x01w\x18\x01 \x03(\x01\x12\t\n\x01\x62\x18\x02 \x03(\x01\"\x1e\n\x0bnote_finish\x12\x0f\n\x07ip_addr\x18\x01 \x01(\t2\xf6\x01\n\x06master\x12\x33\n\x10register_cluster\x12\x0f.protos.cluster\x1a\x0e.protos.status\x12,\n\x0cnotice_train\x12\x0c.protos.note\x1a\x0e.protos.status\x12\x44\n\x1dworker_notice_master_finished\x12\x13.protos.worker_note\x1a\x0e.protos.status\x12\x43\n#ps_notice_master_pull_data_finished\x12\x0c.protos.note\x1a\x0e.protos.status2\xfc\x01\n\x02ps\x12\x33\n\x10register_cluster\x12\x0f.protos.cluster\x1a\x0e.protos.status\x12\x31\n\x0bsend_weight\x12\x0c.protos.step\x1a\x14.protos.array_weight\x12R\n)master_notice_ps_to_pull_data_from_worker\x12\x15.protos.worker_fin_ip\x1a\x0e.protos.status\x12:\n\x1amaster_notice_ps_aggregate\x12\x0c.protos.note\x1a\x0e.protos.status2\xcf\x01\n\x06worker\x12\x33\n\x10register_cluster\x12\x0f.protos.cluster\x1a\x0e.protos.status\x12/\n\x0fsend_train_data\x12\x0c.protos.data\x1a\x0e.protos.status\x12\x32\n\x12notice_start_train\x12\x0c.protos.note\x1a\x0e.protos.status\x12+\n\nsend_delta\x12\x0e.protos.status\x1a\r.protos.deltab\x06proto3')
)




_CLUSTER = _descriptor.Descriptor(
  name='cluster',
  full_name='protos.cluster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ps', full_name='protos.cluster.ps', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workers', full_name='protos.cluster.workers', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer', full_name='protos.cluster.layer', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learn_rate', full_name='protos.cluster.learn_rate', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='protos.cluster.batch_size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='master', full_name='protos.cluster.master', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=129,
)


_STATUS = _descriptor.Descriptor(
  name='status',
  full_name='protos.status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protos.status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mes', full_name='protos.status.mes', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=166,
)


_WORKER_NOTE = _descriptor.Descriptor(
  name='worker_note',
  full_name='protos.worker_note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w_ip', full_name='protos.worker_note.w_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w_f', full_name='protos.worker_note.w_f', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_time', full_name='protos.worker_note.next_time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=227,
)


_WORKER_FIN_IP = _descriptor.Descriptor(
  name='worker_fin_ip',
  full_name='protos.worker_fin_ip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w_ip', full_name='protos.worker_fin_ip.w_ip', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=258,
)


_DATA = _descriptor.Descriptor(
  name='data',
  full_name='protos.data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='protos.data.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_gap', full_name='protos.data.index_gap', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=300,
)


_NOTE = _descriptor.Descriptor(
  name='note',
  full_name='protos.note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notice', full_name='protos.note.notice', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=324,
)


_ARRAY_WEIGHT = _descriptor.Descriptor(
  name='array_weight',
  full_name='protos.array_weight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='protos.array_weight.w', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='protos.array_weight.b', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=362,
)


_STEP = _descriptor.Descriptor(
  name='step',
  full_name='protos.step',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='step_number', full_name='protos.step.step_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=391,
)


_DELTA = _descriptor.Descriptor(
  name='delta',
  full_name='protos.delta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='protos.delta.w', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='protos.delta.b', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=422,
)


_NOTE_FINISH = _descriptor.Descriptor(
  name='note_finish',
  full_name='protos.note_finish',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_addr', full_name='protos.note_finish.ip_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=454,
)

DESCRIPTOR.message_types_by_name['cluster'] = _CLUSTER
DESCRIPTOR.message_types_by_name['status'] = _STATUS
DESCRIPTOR.message_types_by_name['worker_note'] = _WORKER_NOTE
DESCRIPTOR.message_types_by_name['worker_fin_ip'] = _WORKER_FIN_IP
DESCRIPTOR.message_types_by_name['data'] = _DATA
DESCRIPTOR.message_types_by_name['note'] = _NOTE
DESCRIPTOR.message_types_by_name['array_weight'] = _ARRAY_WEIGHT
DESCRIPTOR.message_types_by_name['step'] = _STEP
DESCRIPTOR.message_types_by_name['delta'] = _DELTA
DESCRIPTOR.message_types_by_name['note_finish'] = _NOTE_FINISH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

cluster = _reflection.GeneratedProtocolMessageType('cluster', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTER,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.cluster)
  ))
_sym_db.RegisterMessage(cluster)

status = _reflection.GeneratedProtocolMessageType('status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.status)
  ))
_sym_db.RegisterMessage(status)

worker_note = _reflection.GeneratedProtocolMessageType('worker_note', (_message.Message,), dict(
  DESCRIPTOR = _WORKER_NOTE,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.worker_note)
  ))
_sym_db.RegisterMessage(worker_note)

worker_fin_ip = _reflection.GeneratedProtocolMessageType('worker_fin_ip', (_message.Message,), dict(
  DESCRIPTOR = _WORKER_FIN_IP,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.worker_fin_ip)
  ))
_sym_db.RegisterMessage(worker_fin_ip)

data = _reflection.GeneratedProtocolMessageType('data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.data)
  ))
_sym_db.RegisterMessage(data)

note = _reflection.GeneratedProtocolMessageType('note', (_message.Message,), dict(
  DESCRIPTOR = _NOTE,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.note)
  ))
_sym_db.RegisterMessage(note)

array_weight = _reflection.GeneratedProtocolMessageType('array_weight', (_message.Message,), dict(
  DESCRIPTOR = _ARRAY_WEIGHT,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.array_weight)
  ))
_sym_db.RegisterMessage(array_weight)

step = _reflection.GeneratedProtocolMessageType('step', (_message.Message,), dict(
  DESCRIPTOR = _STEP,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.step)
  ))
_sym_db.RegisterMessage(step)

delta = _reflection.GeneratedProtocolMessageType('delta', (_message.Message,), dict(
  DESCRIPTOR = _DELTA,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.delta)
  ))
_sym_db.RegisterMessage(delta)

note_finish = _reflection.GeneratedProtocolMessageType('note_finish', (_message.Message,), dict(
  DESCRIPTOR = _NOTE_FINISH,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:protos.note_finish)
  ))
_sym_db.RegisterMessage(note_finish)



_MASTER = _descriptor.ServiceDescriptor(
  name='master',
  full_name='protos.master',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=457,
  serialized_end=703,
  methods=[
  _descriptor.MethodDescriptor(
    name='register_cluster',
    full_name='protos.master.register_cluster',
    index=0,
    containing_service=None,
    input_type=_CLUSTER,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='notice_train',
    full_name='protos.master.notice_train',
    index=1,
    containing_service=None,
    input_type=_NOTE,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='worker_notice_master_finished',
    full_name='protos.master.worker_notice_master_finished',
    index=2,
    containing_service=None,
    input_type=_WORKER_NOTE,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ps_notice_master_pull_data_finished',
    full_name='protos.master.ps_notice_master_pull_data_finished',
    index=3,
    containing_service=None,
    input_type=_NOTE,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['master'] = _MASTER


_PS = _descriptor.ServiceDescriptor(
  name='ps',
  full_name='protos.ps',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=706,
  serialized_end=958,
  methods=[
  _descriptor.MethodDescriptor(
    name='register_cluster',
    full_name='protos.ps.register_cluster',
    index=0,
    containing_service=None,
    input_type=_CLUSTER,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='send_weight',
    full_name='protos.ps.send_weight',
    index=1,
    containing_service=None,
    input_type=_STEP,
    output_type=_ARRAY_WEIGHT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='master_notice_ps_to_pull_data_from_worker',
    full_name='protos.ps.master_notice_ps_to_pull_data_from_worker',
    index=2,
    containing_service=None,
    input_type=_WORKER_FIN_IP,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='master_notice_ps_aggregate',
    full_name='protos.ps.master_notice_ps_aggregate',
    index=3,
    containing_service=None,
    input_type=_NOTE,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PS)

DESCRIPTOR.services_by_name['ps'] = _PS


_WORKER = _descriptor.ServiceDescriptor(
  name='worker',
  full_name='protos.worker',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=961,
  serialized_end=1168,
  methods=[
  _descriptor.MethodDescriptor(
    name='register_cluster',
    full_name='protos.worker.register_cluster',
    index=0,
    containing_service=None,
    input_type=_CLUSTER,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='send_train_data',
    full_name='protos.worker.send_train_data',
    index=1,
    containing_service=None,
    input_type=_DATA,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='notice_start_train',
    full_name='protos.worker.notice_start_train',
    index=2,
    containing_service=None,
    input_type=_NOTE,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='send_delta',
    full_name='protos.worker.send_delta',
    index=3,
    containing_service=None,
    input_type=_STATUS,
    output_type=_DELTA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
